[package]
name = "whuh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
itertools = "0.12.1"
nalgebra = "0.32.3"
tobj = "4.0.2"
wavefront_obj = "10.0.0"
